name: Update README

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script to update README
        run: |
          python update_readme.py  # Replace with your script name if different
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./
          commit_user_name: devsdenepal # defaults to "github-actions[bot]"
          commit_user_email: gautamn7822@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: "✅ UPDATE README "
          #push_options: '--force'
