name: Update README

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version if needed

      - name: Install markdown library
        run: |
          python -m pip install --upgrade pip
          pip install markdown

      - name: Run Python script to update README
        run: |
          python update_readme.py  # Replace with your script name if different

      - name: Commit changes to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./
          commit_user_name: devsdenepal
          commit_user_email: gautamn7822@gmail.com
          commit_message: "✅ UPDATE README"
